---
- hosts: web
  gather_facts: no
  become: yes
  roles:
    - nginx
- hosts: app
  gather_facts: no
  become: yes
  roles:
    - docker
  vars:
    lab_path: "/home/beka/Study/DevOps"
    app_path: "/home/vagrant/DevOps/lab-1"
  tasks:
    - name: Delete app directory
      file:
        path: "{{ app_path }}"
        state: absent

    - name: Cloning repository
      git:
        repo: https://github.com/mdn/django-locallibrary-tutorial.git
        dest: "{{ app_path }}"
        clone: yes
        update: yes

    - name: Change settings file
      copy:
        src: "{{ lab_path }}/source/settings.py"
        dest: "{{ app_path}}/locallibrary/"

    - name: Installing requirements from requirements.txt
      pip: 
        requirements: "{{ app_path }}/requirements.txt"
        virtualenv: "{{ app_path }}/venv"

    - name: Make migrations
      command: "python3 {{ app_path }}/manage.py makemigrations"

    - name: Migrate
      command: "python3 {{ app_path }}/manage.py migrate"

    - name: Collect static
      command: "python3 {{ app_path }}/manage.py collectstatic --noinput"

    - name: Run the standard tests
      command: "python3 {{ app_path }}/manage.py test"

    - name: Create a superuser for app
      #command: "python3 {{ app_path }}/manage.py createsuperuser --username vagrant --email vagrant@mail.ru --noinput"
      command: "echo \"from django.contrib.auth.models import User; User.objects.create_superuser('vagrant', 'vagrant@example.com', 'vagrant')\" | python manage.py shell"

    - name: Copy Dockerfile
      copy: 
        src: "{{ lab_path }}/source/Dockerfile"
        dest: "{{ app_path }}"
        remote_src: no

    - name: Stop instance
      shell: "sudo docker rm -f django_app"
      ignore_errors: yes


    - name: Configuration docker image
      docker_image:
        build:
          path: "{{ app_path }}"
        name: django_app
        state: present
        source: build


#    - name: Start docker container
#      docker_container: 
#        name: devops-1
#        image: devops-1:latest
#        exposed_ports: 
#          - "127.0.0.1:80:80/tcp"
#        state: started

    - name: Start docker container
      shell: "sudo docker run -d -p 8080:80 --name django_app django_app:latest"
