web:
  hosts:
    vagrant_web:
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2200
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: /home/beka/Study/DevOps/.vagrant/machines/srv2/virtualbox/private_key
app:
  hosts:
    vagrant_app:
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2222
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: /home/beka/Study/DevOps/.vagrant/machines/srv1/virtualbox/private_key
