---
- hosts: app
  become: yes
  become_method: sudo
  vars:
    lab_path: "/home/beka/Study/DevOps/lab-1"
    app_path: "/home/vagrant/DevOps/lab-1"
  tasks:
    - name: Cloning repository
      git:
        repo: https://github.com/mdn/django-locallibrary-tutorial.git
        dest: "{{ app_path }}"
        clone: yes
        update: yes

    - name: Installing requirements from requirements.txt
      pip: 
        requirements: "{{ app_path }}/requirements.txt"
        virtualenv: "{{ app_path }}/venv"

    - name: Make migrations
      command: "python3 {{ app_path }}/manage.py makemigrations"

    - name: Migrate
      command: "python3 {{ app_path }}/manage.py migrate"

    - name: Collect static
      command: "python3 {{ app_path }}/manage.py collectstatic --noinput"

    - name: Run the standard tests
      command: "python3 {{ app_path }}/manage.py test"

#    - name: Create a superuser for app
#      command: "python3 {{ app_path }}/manage.py createsuperuser --username vagrant --email vagrant@mail.ru --noinput"
#
    - name: Copy Dockerfile
      copy: 
        src: "{{ lab_path }}/source/Dockerfile"
        dest: "{{ app_path }}"
        remote_src: no

    - name: Stop instance
      shell: "sudo docker kill $(sudo docker ps -q) && sudo docker rm -f $(sudo docker ps -a -q)"
      ignore_errors: yes


    - name: Configuration docker image
      docker_image:
        build:
          path: "{{ app_path }}"
        name: devops-1
        state: present
        source: build


#    - name: Start docker container
#      docker_container: 
#        name: devops-1
#        image: devops-1:latest
#        exposed_ports: 
#          - "127.0.0.1:80:80/tcp"
#        state: started

    - name: Start docker container
      shell: "sudo docker run -d -p 80:80 --name devops-1 devops-1:latest"
